# Auto Regression Hands-On

In [1]:
# Ignore warnings
import warnings
warnings.filterwarnings("ignore")

In [2]:
# Import important libraries
import pandas as pd
import yfinance as yf
import datetime as dt
from nsepy import get_history as gh
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error
from statsmodels.tsa.ar_model import AutoReg

In [3]:
stock_symbol = "RELIANCE.NS"
Stk_data =yf.download(stock_symbol, start = "2023-01-01", end = "2023-07-01")
Stk_data.info()

[*********************100%***********************]  1 of 1 completed

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 122 entries, 2023-01-02 to 2023-06-30
Data columns (total 5 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   (Close, RELIANCE.NS)   122 non-null    float64
 1   (High, RELIANCE.NS)    122 non-null    float64
 2   (Low, RELIANCE.NS)     122 non-null    float64
 3   (Open, RELIANCE.NS)    122 non-null    float64
 4   (Volume, RELIANCE.NS)  122 non-null    int64
dtypes: float64(4), int64(1)
memory usage: 5.7 KB

In [4]:
Stk_data

Price             Close         High          Low         Open      Volume
Ticker      RELIANCE.NS  RELIANCE.NS  RELIANCE.NS  RELIANCE.NS RELIANCE.NS
Date
2023-01-02  1170.477905  1171.886546  1157.891121  1158.709022     5316175
2023-01-03  1161.912598  1169.160249  1157.709511  1165.547781     7658932
2023-01-04  1144.418335  1163.730179  1142.350806  1161.889811     9264891
2023-01-05  1142.373413  1152.529209  1137.806748  1146.667484    13637099
2023-01-06  1152.756470  1157.777578  1144.304744  1148.098940     6349597
...                 ...          ...          ...          ...         ...
2023-06-23  1142.691650  1151.166093  1141.442022  1149.121279     6628570
2023-06-26  1133.967041  1142.986789  1130.854450  1139.169878    12641159
2023-06-27  1134.376221  1140.305974  1129.923136  1134.421653     9689466
2023-06-28  1149.393921  1153.188117  1135.012202  1141.896393    11354006
2023-06-30  1158.822510  1161.730656  1151.188686  1157.073127    11151555

[122 rows x 5 columns]

In [5]:
Stk_data = Stk_data[["Close", "High", "Low", "Open"]]
Stk_data

Price             Close         High          Low         Open
Ticker      RELIANCE.NS  RELIANCE.NS  RELIANCE.NS  RELIANCE.NS
Date
2023-01-02  1170.477905  1171.886546  1157.891121  1158.709022
2023-01-03  1161.912598  1169.160249  1157.709511  1165.547781
2023-01-04  1144.418335  1163.730179  1142.350806  1161.889811
2023-01-05  1142.373413  1152.529209  1137.806748  1146.667484
2023-01-06  1152.756470  1157.777578  1144.304744  1148.098940
...                 ...          ...          ...          ...
2023-06-23  1142.691650  1151.166093  1141.442022  1149.121279
2023-06-26  1133.967041  1142.986789  1130.854450  1139.169878
2023-06-27  1134.376221  1140.305974  1129.923136  1134.421653
2023-06-28  1149.393921  1153.188117  1135.012202  1141.896393
2023-06-30  1158.822510  1161.730656  1151.188686  1157.073127

[122 rows x 4 columns]

In [6]:
Column = "Close"

In [7]:
MMS = MinMaxScaler()
Data1 = MMS.fit_transform(Stk_data[[Column]])
print("Length of data is:", Data1.shape)

Length of data is: (122, 1)

In [8]:
Training_size = round(len(Data1)*0.8) # Here 0.8 is a playable parameter. The developer can use different values to get an optimised output.
print(Training_size)
X_train = Data1[:Training_size]
X_test = Data1[Training_size:]
print (f"The length of X_train is: {X_train.shape}")
print (f"The length of X_test is: {X_test.shape}")
# Note: In the case of TSA, the input and output are the same. This is because TSA is univariate analysis
Y_train = X_train
Y_test = X_test

98
The length of X_train is: (98, 1)
The length of X_test is: (24, 1)

In [9]:
Trends = ['n', 't', 'c', 'ct']
Lags = [1,2,3,4]
for i in Lags: 
    # To print i
    for td in Trends: 
        # To print td
        Model = AutoReg(X_train, lags=i, trend=td)
        Model_fit = Model.fit()
        # Making a prediction
        Y_pred = Model_fit.predict(len(X_train), len(Data1-1))
        print ("Lag ={}, Trend ={}".format(i,td))
        rmsemape (Y_test, Y_pred)
        print ("*********")

Lag =1, Trend =n

NameError: name 'rmsemape' is not defined

In [10]:
from stockFunctions import rmsemape

ModuleNotFoundError: No module named 'stockFunctions'